### ISSUE TITLE
Request to change the website URL address

### ISSUE THREAD

**Issue by ghost** [Jainil-coder/Jainil-coder#1]
change website url address (https://prakashanalyst.github.io/) in portfolio website badge from **📱 Connect with Me** section

**Comment by Jainil-coder** [comment]
Sorry Prakash,

**Comment by Jainil-coder** [comment]
I didnt knew that the website url address in portfolio was yours, now I have removed the url you can check.
Thanks

**Comment by Jainil-coder** [comment]
> 
I didnt knew that the website url address in portfolio was yours, now I have removed the url you can check.
Thanks

**Comment by ghost** [comment]
It's fine and Thank you for changing it 👍
